/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface CallerInterface extends utils.Interface {
  functions: {
    "testCallThatDoesNotExist(address)": FunctionFragment;
    "testCallToFoo(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "testCallThatDoesNotExist" | "testCallToFoo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "testCallThatDoesNotExist",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "testCallToFoo",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "testCallThatDoesNotExist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCallToFoo",
    data: BytesLike
  ): Result;

  events: {
    "Response(bool,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Response"): EventFragment;
}

export interface ResponseEventObject {
  success: boolean;
  data: string;
}
export type ResponseEvent = TypedEvent<[boolean, string], ResponseEventObject>;

export type ResponseEventFilter = TypedEventFilter<ResponseEvent>;

export interface Caller extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CallerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    testCallThatDoesNotExist(
      _receiverAddr: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    testCallToFoo(
      _receiverAddr: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  testCallThatDoesNotExist(
    _receiverAddr: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  testCallToFoo(
    _receiverAddr: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    testCallThatDoesNotExist(
      _receiverAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    testCallToFoo(
      _receiverAddr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Response(bool,bytes)"(success?: null, data?: null): ResponseEventFilter;
    Response(success?: null, data?: null): ResponseEventFilter;
  };

  estimateGas: {
    testCallThatDoesNotExist(
      _receiverAddr: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    testCallToFoo(
      _receiverAddr: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    testCallThatDoesNotExist(
      _receiverAddr: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    testCallToFoo(
      _receiverAddr: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
