/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface LocationTrackerInterface extends utils.Interface {
  functions: {
    "addLocation(uint256,string,string)": FunctionFragment;
    "getLocation(uint256)": FunctionFragment;
    "getTrailCount()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "addLocation" | "getLocation" | "getTrailCount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addLocation",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getLocation",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrailCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addLocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrailCount",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LocationTracker extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LocationTrackerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addLocation(
      _locationId: PromiseOrValue<BigNumberish>,
      _name: PromiseOrValue<string>,
      _secret: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getLocation(
      trailNo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, BigNumber, BigNumber, string]>;

    getTrailCount(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  addLocation(
    _locationId: PromiseOrValue<BigNumberish>,
    _name: PromiseOrValue<string>,
    _secret: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getLocation(
    trailNo: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber, BigNumber, BigNumber, string]>;

  getTrailCount(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addLocation(
      _locationId: PromiseOrValue<BigNumberish>,
      _name: PromiseOrValue<string>,
      _secret: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getLocation(
      trailNo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber, BigNumber, BigNumber, string]>;

    getTrailCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    addLocation(
      _locationId: PromiseOrValue<BigNumberish>,
      _name: PromiseOrValue<string>,
      _secret: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getLocation(
      trailNo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTrailCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addLocation(
      _locationId: PromiseOrValue<BigNumberish>,
      _name: PromiseOrValue<string>,
      _secret: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getLocation(
      trailNo: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTrailCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
